# See https://circleci.com/docs/2.0/reusing-config/
version: 2.1

executors:
  python-docker:
    parameters:
      version-python:
        description: "Python version"
        type: string
    docker:
      - image: cimg/python:<<parameters.version-python>>

jobs:
  test:
    parameters:
      version-python:
        description: "Python version"
        type: string
      version-numpy:
        description: "NumPy version"
        type: string
    executor:
      name: python-docker
      version-python: <<parameters.version-python>>
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            sudo apt -qq update
            sudo apt -qq install -y build-essential gcc g++ make python3-pip
            echo "$(command -v python): $(python -V)"
            python -m pip install setuptools numpy==<<parameters.version-numpy>>
      - run:
          name: Build
          command: |
            make
      - run:
          name: Test
          command: |
            make check
      - run:
          name: Stress
          command: |
            make stress

workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              version-python:
                - "3.8"
                - "3.13"
              version-numpy:
                - "1.24.4"
