# See https://circleci.com/docs/2.0/reusing-config/
version: 2.1

executors:
  python-docker:
    parameters:
      version-python:
        description: "Python version"
        type: string
    docker:
      - image: cimg/python:<<parameters.version-python>>
    resource_class: small

jobs:
  test:
    parameters:
      version-python:
        description: "Python version"
        type: string
      prereq-numpy:
        description: "NumPy prerequisite"
        type: string
    executor:
      name: python-docker
      version-python: <<parameters.version-python>>
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            sudo apt -qq update
            sudo apt -qq install -y g++ make time
            echo "$(command -v python): $(python -V)"
            python -m ensurepip --upgrade
            python -m pip install --upgrade setuptools
            python -m pip install '<<parameters.prereq-numpy>>'
      - run:
          name: Build without Python
          command: |
            PYTHON= make
      - run:
          name: Test without Python
          command: |
            PYTHON= make check
      - run:
          name: Build with Python
          command: |
            make
      - run:
          name: Test with Python
          command: |
            make check
      - run:
          name: Stress
          command: |
            make stress

workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              version-python:
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"
                - "3.11"
                - "3.12"
                - "3.13"
              prereq-numpy:
                - "numpy<1.23"
                - "numpy<3"
