# See https://circleci.com/docs/2.0/reusing-config/
version: 2.1

executors:
  python-docker:
    parameters:
      version_python:
        description: "Python version"
        default: "3.9"
        type: string
    docker:
      - image: cimg/python:<<parameters.version_python>>

jobs:
  test:
    parameters:
      version_python:
        description: "Python version"
        default: "3.9"
        type: string
      version_numpy:
        description: "NumPy version"
        default: "1.26.4"
        type: string
    executor:
      name: python-docker
      version: <<parameters.version_python>>
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            sudo apt -qq update
            sudo apt -qq install -y build-essential gcc g++ make python3-pip
            echo "$(command -v python): $(python -V)"
            python -m pip install setuptools pip==<<parameters.version_numpy>>
      - run:
          name: Build
          command: |
            make
      - run:
          name: Test
          command: |
            make check
      - run:
          name: Stress
          command: |
            make stress

workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              version_python:
                - "3.8"
                - "3.13"
              version_numpy:
                - "1.26.4"
